### ISSUE TITLE
Error Message with kvstore

### ISSUE THREAD

**Issue by mattlim1207** [mattlim1207/csci499_mattlim1207#2]
/usr/bin/ld: CMakeFiles/server.dir/kvstore_server.cc.o: in function `kvstore::GetRequest::GetRequest()': kvstore_server.cc:(.text._ZN7kvstore10GetRequestC2Ev[_ZN7kvstore10GetRequestC5Ev]+0x1d): undefined reference to `kvstore::GetRequest::GetRequest(google::protobuf::Arena*)' /usr/bin/ld: CMakeFiles/server.dir/kvstore_server.cc.o: in function `kvstore::GetReply::GetReply()': kvstore_server.cc:(.text._ZN7kvstore8GetReplyC2Ev[_ZN7kvstore8GetReplyC5Ev]+0x1d): undefined reference to `kvstore::GetReply::GetReply(google::protobuf::Arena*)' /usr/bin/ld: CMakeFiles/server.dir/kvstore_server.cc.o: in function `KeyValueStoreServiceImpl::getValue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)': kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImpl8getValueENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN24KeyValueStoreServiceImpl8getValueENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x56): undefined reference to `KeyValueStoreServiceImpl::storage[abi:cxx11]' /usr/bin/ld: kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImpl8getValueENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN24KeyValueStoreServiceImpl8getValueENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x66): undefined reference to `KeyValueStoreServiceImpl::storage[abi:cxx11]' /usr/bin/ld: CMakeFiles/server.dir/kvstore_server.cc.o: in function `KeyValueStoreServiceImpl::put(grpc::ServerContext*, kvstore::PutRequest const*, kvstore::PutReply*)': kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImpl3putEPN4grpc13ServerContextEPKN7kvstore10PutRequestEPNS3_8PutReplyE[_ZN24KeyValueStoreServiceImpl3putEPN4grpc13ServerContextEPKN7kvstore10PutRequestEPNS3_8PutReplyE]+0x93): undefined reference to `KeyValueStoreServiceImpl::storage[abi:cxx11]' /usr/bin/ld: CMakeFiles/server.dir/kvstore_server.cc.o: in function `KeyValueStoreServiceImpl::get(grpc::ServerContext*, grpc::ServerReaderWriter<kvstore::GetReply, kvstore::GetRequest>*)': kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE[_ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE]+0x125): undefined reference to `kvstore::GetReply::~GetReply()' /usr/bin/ld: kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE[_ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE]+0x153): undefined reference to `kvstore::GetRequest::~GetRequest()' /usr/bin/ld: kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE[_ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE]+0x1ba): undefined reference to `kvstore::GetReply::~GetReply()' /usr/bin/ld: kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE[_ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE]+0x1d2): undefined reference to `kvstore::GetRequest::~GetRequest()' /usr/bin/ld: CMakeFiles/server.dir/kvstore_server.cc.o: in function `KeyValueStoreServiceImpl::remove(grpc::ServerContext*, kvstore::RemoveRequest const*, kvstore::RemoveReply*)': kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImpl6removeEPN4grpc13ServerContextEPKN7kvstore13RemoveRequestEPNS3_11RemoveReplyE[_ZN24KeyValueStoreServiceImpl6removeEPN4grpc13ServerContextEPKN7kvstore13RemoveRequestEPNS3_11RemoveReplyE]+0x32): undefined reference to `KeyValueStoreServiceImpl::storage[abi:cxx11]' /usr/bin/ld: CMakeFiles/server.dir/kvstore_server.cc.o: in function `KeyValueStoreServiceImpl::KeyValueStoreServiceImpl()': kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImplC2Ev[_ZN24KeyValueStoreServiceImplC5Ev]+0x18): undefined reference to `kvstore::KeyValueStore::Service::Service()' /usr/bin/ld: CMakeFiles/server.dir/kvstore_server.cc.o: in function `KeyValueStoreServiceImpl::~KeyValueStoreServiceImpl()': kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImplD2Ev[_ZN24KeyValueStoreServiceImplD5Ev]+0x26): undefined reference to `kvstore::KeyValueStore::Service::~Service()' /usr/bin/ld: CMakeFiles/server.dir/kvstore_server.cc.o:(.data.rel.ro._ZTI24KeyValueStoreServiceImpl[_ZTI24KeyValueStoreServiceImpl]+0x10): undefined reference to `typeinfo for kvstore::KeyValueStore::Service' collect2: error: ld returned 1 exit status make[3]: *** [CMakeFiles/server.dir/build.make:124: server] Error 1 make[2]: *** [CMakeFiles/Makefile2:1002: CMakeFiles/server.dir/all] Error 2 make[1]: *** [CMakeFiles/Makefile2:1009: CMakeFiles/server.dir/rule] Error 2 make: *** [Makefile:177: server] Error 2 @adamegyed @barath

**Comment by mattlim1207** [comment]
I managed to get it down to this by simply fixing things I just placed within the wrong scope. However, the rest I'm not sure how to do. I tried reinstalling grpc and recompiling my proto file, to no avail:
/usr/bin/ld: CMakeFiles/server.dir/kvstore_server.cc.o: in function `kvstore::GetRequest::GetRequest()':
kvstore_server.cc:(.text._ZN7kvstore10GetRequestC2Ev[_ZN7kvstore10GetRequestC5Ev]+0x1d): undefined reference to `kvstore::GetRequest::GetRequest(google::protobuf::Arena*)'
/usr/bin/ld: CMakeFiles/server.dir/kvstore_server.cc.o: in function `kvstore::GetReply::GetReply()':
kvstore_server.cc:(.text._ZN7kvstore8GetReplyC2Ev[_ZN7kvstore8GetReplyC5Ev]+0x1d): undefined reference to `kvstore::GetReply::GetReply(google::protobuf::Arena*)'
/usr/bin/ld: CMakeFiles/server.dir/kvstore_server.cc.o: in function `KeyValueStoreServiceImpl::get(grpc::ServerContext*, grpc::ServerReaderWriter<kvstore::GetReply, kvstore::GetRequest>*)':
kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE[_ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE]+0x125): undefined reference to `kvstore::GetReply::~GetReply()'
/usr/bin/ld: kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE[_ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE]+0x153): undefined reference to `kvstore::GetRequest::~GetRequest()'
/usr/bin/ld: kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE[_ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE]+0x1ba): undefined reference to `kvstore::GetReply::~GetReply()'
/usr/bin/ld: kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE[_ZN24KeyValueStoreServiceImpl3getEPN4grpc13ServerContextEPNS0_18ServerReaderWriterIN7kvstore8GetReplyENS4_10GetRequestEEE]+0x1d2): undefined reference to `kvstore::GetRequest::~GetRequest()'
/usr/bin/ld: CMakeFiles/server.dir/kvstore_server.cc.o: in function `KeyValueStoreServiceImpl::KeyValueStoreServiceImpl()':
kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImplC2Ev[_ZN24KeyValueStoreServiceImplC5Ev]+0x18): undefined reference to `kvstore::KeyValueStore::Service::Service()'
/usr/bin/ld: CMakeFiles/server.dir/kvstore_server.cc.o: in function `KeyValueStoreServiceImpl::~KeyValueStoreServiceImpl()':
kvstore_server.cc:(.text._ZN24KeyValueStoreServiceImplD2Ev[_ZN24KeyValueStoreServiceImplD5Ev]+0x26): undefined reference to `kvstore::KeyValueStore::Service::~Service()'
/usr/bin/ld: CMakeFiles/server.dir/kvstore_server.cc.o:(.data.rel.ro._ZTI24KeyValueStoreServiceImpl[_ZTI24KeyValueStoreServiceImpl]+0x10): undefined reference to `typeinfo for kvstore::KeyValueStore::Service'

**Comment by mattlim1207** [comment]
I'm starting to think it's a problem with my proto file compiling, as when I try to compile the proto file in the grpc examples, it runs into version errors. However, i don't have any duplicate installs of protoc and looking through the code, it seems impossible for the error being thrown to be true, so it might be a problem with other environment things.

**Comment by barath** [comment]
Could you also point us to the latest version of your code?

**Comment by mattlim1207** [comment]
I just pushed to a new branch called 'kvstore', that should include all the latest versions of the relevant files (proto files and server)

**Comment by adamegyed** [comment]
@mattlim1207 This seems like it would be an issue with the linking step of either the generated protobuf/grpc sources or the library sources themselves. I think you might need to rearrange the order of some of your grpc/protobuf initialization code in `CMakeLists.txt`, and possibly add some extra functionality as well. If you'd like to try to resolve these issues yourself, see the example `CMakeLists.txt` in https://github.com/grpc/grpc/tree/master/examples/cpp/helloworld.

It's fairly difficult to debug these asynchronously, would you be able to come to one of my office hours? Or, feel free to email me to schedule custom office hours at a time that works for you.
